#!/bin/bash
# scripts/compound/auto-compound.sh
# Full pipeline: report → PRD → tasks → implementation → PR
# Adapted for Ubuntu/WSL

set -e

# Configuration
PROJECT_DIR="$HOME/empowered-visual"
LOG_FILE="$PROJECT_DIR/logs/auto-compound-$(date +%Y-%m-%d).log"
MAX_ITERATIONS=15

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "=== Starting Auto-Compound Pipeline ==="

cd "$PROJECT_DIR"

# Load any environment variables
if [ -f .env.local ]; then
    source .env.local
fi

# Fetch latest (including tonight's CLAUDE.md updates)
log "Fetching latest from origin..."
git fetch origin main
git checkout main
git reset --hard origin/main

# Check for reports
if [ ! -d "reports" ] || [ -z "$(ls -A reports/*.md 2>/dev/null)" ]; then
    log "No reports found in reports/. Creating sample report..."

    # Create a sample report based on current project state
    cat > "reports/daily-$(date +%Y-%m-%d).md" << 'REPORT'
# Daily Report - $(date +%Y-%m-%d)

## Status
- Visual companion in development
- Basic chapter structure complete

## Priorities
1. Add more Mermaid diagrams to chapters that are text-heavy
2. Enhance learning paths with cross-references
3. Add interactive elements to concept pages

## Quality Notes
- Build passes
- No broken links detected
REPORT

    log "Sample report created. Edit reports/daily-$(date +%Y-%m-%d).md with real priorities."
    exit 0
fi

# Find the latest report
LATEST_REPORT=$(ls -t reports/*.md 2>/dev/null | head -1)
log "Using report: $LATEST_REPORT"

# Create a unique branch name
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="compound/auto-$TIMESTAMP"

log "Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Have Claude analyze the report and create a PRD
log "Analyzing report and creating PRD..."
claude -p "Read the file $LATEST_REPORT

Analyze this report and:
1. Identify the #1 highest priority item that can be completed in one session
2. Create a PRD (Product Requirements Document) for this item
3. Save the PRD to tasks/prd-$TIMESTAMP.md

The PRD should include:
- Title
- User Story (As a... I want... So that...)
- Acceptance Criteria (testable, specific)
- Technical Approach
- Files to modify

Keep it focused - one small, completable task." --dangerously-skip-permissions 2>&1 | tee -a "$LOG_FILE"

# Check if PRD was created
PRD_FILE="tasks/prd-$TIMESTAMP.md"
if [ ! -f "$PRD_FILE" ]; then
    log "ERROR: PRD was not created. Aborting."
    git checkout main
    git branch -D "$BRANCH_NAME"
    exit 1
fi

log "PRD created: $PRD_FILE"

# Create prd.json for the loop
log "Converting PRD to task list..."
claude -p "Read the PRD at $PRD_FILE

Convert it to a JSON task file at prd.json with this structure:
{
  \"title\": \"Task title\",
  \"userStories\": [
    {
      \"id\": 1,
      \"title\": \"Story title\",
      \"acceptanceCriteria\": \"Specific testable criteria\",
      \"passes\": false
    }
  ]
}

Break the work into 1-3 small user stories. Each should be independently testable." --dangerously-skip-permissions 2>&1 | tee -a "$LOG_FILE"

# Run the execution loop
log "Starting execution loop..."
"$PROJECT_DIR/scripts/compound/loop.sh" "$MAX_ITERATIONS" 2>&1 | tee -a "$LOG_FILE"

# Check if all tasks passed (works without jq)
if [ -f "prd.json" ]; then
    REMAINING=$(grep -c '"passes": false' prd.json 2>/dev/null || echo "0")
    if [ "$REMAINING" -eq 0 ]; then
        log "All tasks completed successfully!"
    else
        log "Warning: $REMAINING tasks did not pass"
    fi
fi

# Push and create PR
log "Pushing branch and creating PR..."
git push -u origin "$BRANCH_NAME"

# Extract title from PRD for PR
PR_TITLE=$(head -1 "$PRD_FILE" | sed 's/^#\s*//' | head -c 60)
if [ -z "$PR_TITLE" ]; then
    PR_TITLE="Compound: Auto-generated improvements"
fi

gh pr create --draft \
    --title "$PR_TITLE" \
    --body "$(cat <<EOF
## Summary
Auto-generated by compound engineering pipeline.

## Source
- Report: $LATEST_REPORT
- PRD: $PRD_FILE

## Changes
$(git log main.."$BRANCH_NAME" --oneline)

---
🤖 Generated by Compound Engineering System
EOF
)" 2>&1 | tee -a "$LOG_FILE"

log "=== Auto-Compound Pipeline Complete ==="
